name: itersolv
channels:
        - conda-forge
        - defaults
dependencies:
        - hydra-core
        - ipython  # local-only
        - ipykernel  # local-only
        - ipywidgets  # local-only
        - notebook  # local-only
        - numpy
        - openai
        - pandas
        - python 3.10.6 
        - seaborn
        - sympy
        - tqdm  # local-only
        - wandb
